# Change these first
owner: mschirrmeister # Your GitHub organization or username, where this repository lives
repo: upptime-loopx # The name of this repository

sites:
  - name: Do53 Roost IPv4 UDP
    url: http://107.189.10.142:9202
  - name: Do53 Roost IPv4 TCP
    url: http://107.189.10.142:9203
  - name: Do53 Roost IPv6 UDP
    url: http://107.189.10.142:9204
  - name: Do53 Roost IPv6 TCP
    url: http://107.189.10.142:9205

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: uptime.dns.loopx.org
  baseUrl: /upptime-loopx
  logoUrl: https://uxwing.com/wp-content/themes/uxwing/download/domain-hosting/dns-icon.png
  name: LoopX DNS status
  introTitle: "**LoopX DNS** is a secure and privacy focused DNS service."
  introMessage: LoopX DNS** is a secure and privacy focused DNS service.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
